# version: "3.4"

services:

  task-read:
    container_name: task-read
    #    image: dmitryx/incidents-volcanoes:latest
    build:
      context: .
      dockerfile: src/microservices/TaskService/TaskRead/Dockerfile
    ports:
      - "6002:8001"
    volumes:
      - ./src/microservices/TaskService/TaskRead/Properties/config.Development.json:/app/config.Development.json
    environment:
      - ASPNETCORE_URLS=http://+:8001
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA_TOPIC=FluxManageEvents
      - APP_CONFIG_PATH=/app/config.Development.json
    develop:
      watch:
        - action: rebuild
          path: src/microservices/TaskService/TaskRead
          target: /app
    networks:
      - fluxmanage

  task-write:
    container_name: task-write
    #    image: dmitryx/incidents-volcanoes:latest
    build:
      context: .
      dockerfile: src/microservices/TaskService/TaskWrite/Dockerfile
    ports:
      - "6001:8001"
    volumes:
      - ./src/microservices/TaskService/TaskWrite/Properties/config.Development.json:/app/config.Development.json
    environment:
      - ASPNETCORE_URLS=http://+:8001
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA_TOPIC=FluxManageEvents
      - APP_CONFIG_PATH=/app/config.Development.json
    develop:
      watch:
        - action: rebuild
          path: src/microservices/TaskService/TaskWrite
          target: /app
    networks:
      - fluxmanage

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fluxmanage

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - fluxmanage
      
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - fluxmanage

  frontend:
    container_name: frontend
    build:
      context: ./src/client/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://gateway:8000
    depends_on:
      - gateway
    networks:
      - fluxmanage
      
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/Gateway/gateway.json:/app/gateway.json
    networks:
      - fluxmanage
    
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local


networks:
  fluxmanage:
    driver: bridge
